name: Node.js CI and Deploy to GCS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm cache clean --force
    - run: rm -rf node_modules package-lock.json
    - run: npm install

    - name: Print Node.js Version
      run: node -v

    - name: Print NPM Version
      run: npm -v

    - name: Install Dependencies
      run: npm ci

    - run: npm run build --if-present
      env:
        CI: false  # Disable treating warnings as errors

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Install Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Deploy to Google Cloud Storage
      run: gsutil -m rsync -r build/ gs://awwdudee-portfolio
